


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."currency" AS ENUM (
    'EUR',
    'USD',
    'GBP'
);


ALTER TYPE "public"."currency" OWNER TO "postgres";


CREATE TYPE "public"."issue_category" AS ENUM (
    'ELECTRICAL',
    'PLUMBING',
    'CARPENTRY',
    'GENERAL'
);


ALTER TYPE "public"."issue_category" OWNER TO "postgres";


CREATE TYPE "public"."payment_status" AS ENUM (
    'PENDING',
    'SUCCEEDED',
    'FAILED'
);


ALTER TYPE "public"."payment_status" OWNER TO "postgres";


CREATE TYPE "public"."role_enum" AS ENUM (
    'TENANT',
    'CONTRACTOR',
    'REPRESENTATIVE',
    'ADMIN'
);


ALTER TYPE "public"."role_enum" OWNER TO "postgres";


CREATE TYPE "public"."specialization" AS ENUM (
    'ELECTRICIAN',
    'PLUMBER',
    'CARPENTER',
    'PAINTER'
);


ALTER TYPE "public"."specialization" OWNER TO "postgres";


CREATE TYPE "public"."ticket_status" AS ENUM (
    'OPEN',
    'IN_PROGRESS',
    'RESOLVED'
);


ALTER TYPE "public"."ticket_status" OWNER TO "postgres";


CREATE TYPE "public"."user_role" AS ENUM (
    'TENANT',
    'CONTRACTOR',
    'REPRESENTATIVE',
    'ADMIN'
);


ALTER TYPE "public"."user_role" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."building" (
    "building_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "address" "text" NOT NULL,
    "postal_code" bigint NOT NULL
);


ALTER TABLE "public"."building" OWNER TO "postgres";


ALTER TABLE "public"."building" ALTER COLUMN "building_id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."building_building_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."building_unit" (
    "unit_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "building_id" bigint NOT NULL,
    "label" "text" NOT NULL,
    "floor" smallint NOT NULL
);


ALTER TABLE "public"."building_unit" OWNER TO "postgres";


ALTER TABLE "public"."building_unit" ALTER COLUMN "unit_id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."building_unit_unit_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."city" (
    "postal_code" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."city" OWNER TO "postgres";


ALTER TABLE "public"."city" ALTER COLUMN "postal_code" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."city_postal_code_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."contractor" (
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "phone" "text" NOT NULL,
    "specialization" "public"."specialization" NOT NULL,
    "company_name" "text" DEFAULT ''::"text",
    "rating_avg" double precision DEFAULT 0 NOT NULL,
    "assignments" bigint[]
);


ALTER TABLE "public"."contractor" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."invitation" (
    "invitation_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "from_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "to_id" "uuid" DEFAULT "auth"."uid"() NOT NULL
);


ALTER TABLE "public"."invitation" OWNER TO "postgres";


ALTER TABLE "public"."invitation" ALTER COLUMN "invitation_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."invitation_invitation_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."membership" (
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "price" real DEFAULT 0 NOT NULL,
    "is_active" boolean DEFAULT true,
    "expires_at" timestamp without time zone,
    "last_paid" timestamp without time zone,
    "currency" "public"."currency" DEFAULT 'EUR'::"public"."currency" NOT NULL
);


ALTER TABLE "public"."membership" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."monthly_report" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "building_id" bigint NOT NULL,
    "month" smallint,
    "year" smallint,
    "file_path" "text"
);


ALTER TABLE "public"."monthly_report" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."photo" (
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "ticket_id" bigint NOT NULL,
    "photo_id" bigint NOT NULL,
    "photo_url" "text"
);


ALTER TABLE "public"."photo" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profile" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "role" "public"."role_enum" NOT NULL,
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "email" "text" NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL
);


ALTER TABLE "public"."profile" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."rating" (
    "rating_id" bigint NOT NULL,
    "contractor_id" "uuid" NOT NULL,
    "ticket_id" bigint NOT NULL,
    "ticket_created_by" "uuid" NOT NULL,
    "ticket_unit_id" bigint NOT NULL,
    "reviewer_id" "uuid" NOT NULL,
    "rating" smallint NOT NULL,
    "comment" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "rating_rating_check" CHECK ((("rating" >= 1) AND ("rating" <= 5)))
);


ALTER TABLE "public"."rating" OWNER TO "postgres";


ALTER TABLE "public"."rating" ALTER COLUMN "rating_id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."rating_rating_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."representative" (
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "building_id" bigint NOT NULL
);


ALTER TABLE "public"."representative" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tenant" (
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "building_id" bigint NOT NULL,
    "unit_id" bigint NOT NULL
);


ALTER TABLE "public"."tenant" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."ticket" (
    "ticket_id" bigint NOT NULL,
    "created_by" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "unit_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "issue_category" "public"."issue_category" NOT NULL,
    "description" "text",
    "building_id" bigint NOT NULL,
    "assigned_to" "uuid" DEFAULT "auth"."uid"(),
    "status" "public"."ticket_status" DEFAULT 'OPEN'::"public"."ticket_status" NOT NULL,
    "resolved_at" timestamp without time zone,
    "comment" "text"
);


ALTER TABLE "public"."ticket" OWNER TO "postgres";


ALTER TABLE "public"."ticket" ALTER COLUMN "ticket_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ticket_ticket_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."building"
    ADD CONSTRAINT "building_pkey" PRIMARY KEY ("building_id");



ALTER TABLE ONLY "public"."building_unit"
    ADD CONSTRAINT "building_unit_pkey" PRIMARY KEY ("unit_id", "building_id");



ALTER TABLE ONLY "public"."building_unit"
    ADD CONSTRAINT "building_unit_unit_id_key" UNIQUE ("unit_id");



ALTER TABLE ONLY "public"."city"
    ADD CONSTRAINT "city_pkey" PRIMARY KEY ("postal_code");



ALTER TABLE ONLY "public"."contractor"
    ADD CONSTRAINT "contractor_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."invitation"
    ADD CONSTRAINT "invitation_from_id_key" UNIQUE ("from_id");



ALTER TABLE ONLY "public"."invitation"
    ADD CONSTRAINT "invitation_pkey" PRIMARY KEY ("invitation_id");



ALTER TABLE ONLY "public"."invitation"
    ADD CONSTRAINT "invitation_to_id_key" UNIQUE ("to_id");



ALTER TABLE ONLY "public"."membership"
    ADD CONSTRAINT "membership_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."monthly_report"
    ADD CONSTRAINT "monthly_report_pkey" PRIMARY KEY ("building_id");



ALTER TABLE ONLY "public"."photo"
    ADD CONSTRAINT "photo_photo_id_key" UNIQUE ("photo_id");



ALTER TABLE ONLY "public"."photo"
    ADD CONSTRAINT "photo_pkey" PRIMARY KEY ("photo_id");



ALTER TABLE ONLY "public"."photo"
    ADD CONSTRAINT "photo_ticket_id_key" UNIQUE ("ticket_id");



ALTER TABLE ONLY "public"."profile"
    ADD CONSTRAINT "profile_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."profile"
    ADD CONSTRAINT "profile_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."rating"
    ADD CONSTRAINT "rating_one_per_ticket" UNIQUE ("ticket_id");



ALTER TABLE ONLY "public"."rating"
    ADD CONSTRAINT "rating_pkey" PRIMARY KEY ("rating_id");



ALTER TABLE ONLY "public"."representative"
    ADD CONSTRAINT "representative_building_id_key" UNIQUE ("building_id");



ALTER TABLE ONLY "public"."representative"
    ADD CONSTRAINT "representative_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."tenant"
    ADD CONSTRAINT "tenant_building_id_key" UNIQUE ("building_id");



ALTER TABLE ONLY "public"."tenant"
    ADD CONSTRAINT "tenant_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."tenant"
    ADD CONSTRAINT "tenant_unit_id_key" UNIQUE ("unit_id");



ALTER TABLE ONLY "public"."ticket"
    ADD CONSTRAINT "ticket_pkey" PRIMARY KEY ("ticket_id", "created_by", "unit_id");



ALTER TABLE ONLY "public"."ticket"
    ADD CONSTRAINT "ticket_ticket_id_key" UNIQUE ("ticket_id");



ALTER TABLE ONLY "public"."ticket"
    ADD CONSTRAINT "ticket_unit_id_key" UNIQUE ("unit_id");



CREATE INDEX "idx_building_unit_building" ON "public"."building_unit" USING "btree" ("building_id");



CREATE INDEX "idx_rating_contractor" ON "public"."rating" USING "btree" ("contractor_id");



CREATE INDEX "idx_rating_ticket" ON "public"."rating" USING "btree" ("ticket_id");



CREATE INDEX "idx_ticket_assigned_to" ON "public"."ticket" USING "btree" ("assigned_to");



CREATE INDEX "idx_ticket_building" ON "public"."ticket" USING "btree" ("building_id");



CREATE INDEX "idx_ticket_created_by" ON "public"."ticket" USING "btree" ("created_by");



CREATE INDEX "idx_ticket_issue_category" ON "public"."ticket" USING "btree" ("issue_category");



CREATE INDEX "idx_ticket_status" ON "public"."ticket" USING "btree" ("status");



ALTER TABLE ONLY "public"."building"
    ADD CONSTRAINT "building_postal_code_fkey" FOREIGN KEY ("postal_code") REFERENCES "public"."city"("postal_code") ON UPDATE RESTRICT ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."contractor"
    ADD CONSTRAINT "contractor_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profile"("user_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."invitation"
    ADD CONSTRAINT "invitation_from_id_fkey" FOREIGN KEY ("from_id") REFERENCES "public"."representative"("user_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."invitation"
    ADD CONSTRAINT "invitation_to_id_fkey" FOREIGN KEY ("to_id") REFERENCES "public"."tenant"("user_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."membership"
    ADD CONSTRAINT "membership_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."contractor"("user_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."monthly_report"
    ADD CONSTRAINT "monthly_report_building_id_fkey" FOREIGN KEY ("building_id") REFERENCES "public"."building"("building_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."photo"
    ADD CONSTRAINT "photo_ticket_id_fkey" FOREIGN KEY ("ticket_id") REFERENCES "public"."ticket"("ticket_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."photo"
    ADD CONSTRAINT "photo_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."tenant"("user_id");



ALTER TABLE ONLY "public"."profile"
    ADD CONSTRAINT "profile_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."rating"
    ADD CONSTRAINT "rating_contractor_id_fkey" FOREIGN KEY ("contractor_id") REFERENCES "public"."contractor"("user_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."rating"
    ADD CONSTRAINT "rating_reviewer_id_fkey" FOREIGN KEY ("reviewer_id") REFERENCES "public"."profile"("user_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."rating"
    ADD CONSTRAINT "rating_ticket_fkey" FOREIGN KEY ("ticket_id", "ticket_created_by", "ticket_unit_id") REFERENCES "public"."ticket"("ticket_id", "created_by", "unit_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."representative"
    ADD CONSTRAINT "representative_building_id_fkey" FOREIGN KEY ("building_id") REFERENCES "public"."building"("building_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."representative"
    ADD CONSTRAINT "representative_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profile"("user_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tenant"
    ADD CONSTRAINT "tenant_building_id_fkey" FOREIGN KEY ("building_id") REFERENCES "public"."building"("building_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tenant"
    ADD CONSTRAINT "tenant_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "public"."building_unit"("unit_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tenant"
    ADD CONSTRAINT "tenant_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profile"("user_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ticket"
    ADD CONSTRAINT "ticket_assigned_to_fkey" FOREIGN KEY ("assigned_to") REFERENCES "public"."profile"("user_id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."ticket"
    ADD CONSTRAINT "ticket_building_id_fkey" FOREIGN KEY ("building_id") REFERENCES "public"."building"("building_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."ticket"
    ADD CONSTRAINT "ticket_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."tenant"("user_id");



ALTER TABLE ONLY "public"."ticket"
    ADD CONSTRAINT "ticket_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "public"."building_unit"("unit_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."building_unit"
    ADD CONSTRAINT "unit_building_id_fkey" FOREIGN KEY ("building_id") REFERENCES "public"."building"("building_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE "public"."building" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."building_unit" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."city" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."contractor" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."invitation" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."membership" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."monthly_report" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."photo" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profile" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."rating" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."representative" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tenant" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ticket" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."building" TO "anon";
GRANT ALL ON TABLE "public"."building" TO "authenticated";
GRANT ALL ON TABLE "public"."building" TO "service_role";



GRANT ALL ON SEQUENCE "public"."building_building_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."building_building_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."building_building_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."building_unit" TO "anon";
GRANT ALL ON TABLE "public"."building_unit" TO "authenticated";
GRANT ALL ON TABLE "public"."building_unit" TO "service_role";



GRANT ALL ON SEQUENCE "public"."building_unit_unit_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."building_unit_unit_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."building_unit_unit_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."city" TO "anon";
GRANT ALL ON TABLE "public"."city" TO "authenticated";
GRANT ALL ON TABLE "public"."city" TO "service_role";



GRANT ALL ON SEQUENCE "public"."city_postal_code_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."city_postal_code_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."city_postal_code_seq" TO "service_role";



GRANT ALL ON TABLE "public"."contractor" TO "anon";
GRANT ALL ON TABLE "public"."contractor" TO "authenticated";
GRANT ALL ON TABLE "public"."contractor" TO "service_role";



GRANT ALL ON TABLE "public"."invitation" TO "anon";
GRANT ALL ON TABLE "public"."invitation" TO "authenticated";
GRANT ALL ON TABLE "public"."invitation" TO "service_role";



GRANT ALL ON SEQUENCE "public"."invitation_invitation_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."invitation_invitation_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."invitation_invitation_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."membership" TO "anon";
GRANT ALL ON TABLE "public"."membership" TO "authenticated";
GRANT ALL ON TABLE "public"."membership" TO "service_role";



GRANT ALL ON TABLE "public"."monthly_report" TO "anon";
GRANT ALL ON TABLE "public"."monthly_report" TO "authenticated";
GRANT ALL ON TABLE "public"."monthly_report" TO "service_role";



GRANT ALL ON TABLE "public"."photo" TO "anon";
GRANT ALL ON TABLE "public"."photo" TO "authenticated";
GRANT ALL ON TABLE "public"."photo" TO "service_role";



GRANT ALL ON TABLE "public"."profile" TO "anon";
GRANT ALL ON TABLE "public"."profile" TO "authenticated";
GRANT ALL ON TABLE "public"."profile" TO "service_role";



GRANT ALL ON TABLE "public"."rating" TO "anon";
GRANT ALL ON TABLE "public"."rating" TO "authenticated";
GRANT ALL ON TABLE "public"."rating" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rating_rating_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rating_rating_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rating_rating_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."representative" TO "anon";
GRANT ALL ON TABLE "public"."representative" TO "authenticated";
GRANT ALL ON TABLE "public"."representative" TO "service_role";



GRANT ALL ON TABLE "public"."tenant" TO "anon";
GRANT ALL ON TABLE "public"."tenant" TO "authenticated";
GRANT ALL ON TABLE "public"."tenant" TO "service_role";



GRANT ALL ON TABLE "public"."ticket" TO "anon";
GRANT ALL ON TABLE "public"."ticket" TO "authenticated";
GRANT ALL ON TABLE "public"."ticket" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ticket_ticket_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ticket_ticket_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ticket_ticket_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































RESET ALL;

