alter table "public"."photo" drop constraint "photo_user_id_fkey";

alter table "public"."rating" drop constraint "rating_contractor_id_fkey";

alter table "public"."rating" drop constraint "rating_reviewer_id_fkey";

alter table "public"."tenant" drop constraint "tenant_building_id_fkey";

alter table "public"."ticket" drop constraint "ticket_building_id_fkey";

alter table "public"."ticket" drop constraint "ticket_assigned_to_fkey";

alter table "public"."building_unit" drop constraint "building_unit_pkey";

drop index if exists "public"."idx_rating_contractor";

drop index if exists "public"."idx_ticket_building";

drop index if exists "public"."building_unit_pkey";

alter table "public"."building_unit" alter column "unit_id" set generated by default;

alter table "public"."contractor" drop column "rating_avg";

alter table "public"."photo" drop column "user_id";

alter table "public"."rating" drop column "contractor_id";

alter table "public"."rating" drop column "reviewer_id";

alter table "public"."rating" drop column "ticket_created_by";

alter table "public"."rating" drop column "ticket_unit_id";

alter table "public"."tenant" drop column "building_id";

alter table "public"."tenant" alter column "created_at" set default now();

alter table "public"."ticket" drop column "building_id";

CREATE UNIQUE INDEX building_unit_pkey ON public.building_unit USING btree (unit_id);

alter table "public"."building_unit" add constraint "building_unit_pkey" PRIMARY KEY using index "building_unit_pkey";

alter table "public"."ticket" add constraint "ticket_assigned_to_fkey" FOREIGN KEY (assigned_to) REFERENCES contractor(user_id) not valid;

alter table "public"."ticket" validate constraint "ticket_assigned_to_fkey";



