alter table "public"."building" drop constraint "building_postal_code_fkey";

alter table "public"."invitation" drop constraint "invitation_from_id_key";

alter table "public"."invitation" drop constraint "invitation_to_id_key";

alter table "public"."photo" drop constraint "photo_ticket_id_key";

alter table "public"."rating" drop constraint "rating_ticket_fkey";

alter table "public"."tenant" drop constraint "tenant_building_id_key";

alter table "public"."tenant" drop constraint "tenant_unit_id_key";

alter table "public"."ticket" drop constraint "ticket_unit_id_key";

alter table "public"."city" drop constraint "city_pkey";

alter table "public"."monthly_report" drop constraint "monthly_report_pkey";

alter table "public"."ticket" drop constraint "ticket_pkey";

drop index if exists "public"."city_pkey";

drop index if exists "public"."invitation_from_id_key";

drop index if exists "public"."invitation_to_id_key";

drop index if exists "public"."photo_ticket_id_key";

drop index if exists "public"."tenant_building_id_key";

drop index if exists "public"."tenant_unit_id_key";

drop index if exists "public"."ticket_unit_id_key";

drop index if exists "public"."monthly_report_pkey";

drop index if exists "public"."ticket_pkey";

drop table "public"."city";

alter table "public"."building" alter column "building_id" set generated by default;

alter table "public"."contractor" drop column "assignments";

alter table "public"."monthly_report" alter column "month" set not null;

alter table "public"."monthly_report" alter column "year" set not null;

alter table "public"."rating" alter column "rating_id" set generated by default;

alter table "public"."ticket" add column "title" text not null;

CREATE UNIQUE INDEX monthly_report_pkey ON public.monthly_report USING btree (building_id, month, year);

CREATE UNIQUE INDEX ticket_pkey ON public.ticket USING btree (ticket_id);

alter table "public"."monthly_report" add constraint "monthly_report_pkey" PRIMARY KEY using index "monthly_report_pkey";

alter table "public"."ticket" add constraint "ticket_pkey" PRIMARY KEY using index "ticket_pkey";

alter table "public"."rating" add constraint "rating_ticket_id_fkey" FOREIGN KEY (ticket_id) REFERENCES ticket(ticket_id) not valid;

alter table "public"."rating" validate constraint "rating_ticket_id_fkey";



