alter table "public"."invitation" drop constraint "invitation_to_id_fkey";

alter table "public"."invitation" drop column "to_id";

alter table "public"."invitation" add column "to_email" text not null;

alter table "public"."membership" drop column "is_active";

alter table "public"."photo" alter column "photo_id" add generated by default as identity;

drop type "public"."user_role";



  create policy "Give users authenticated access to folder 133n0pu_0"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (((bucket_id = 'ticket-photos'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "Give users authenticated access to folder 133n0pu_1"
  on "storage"."objects"
  as permissive
  for select
  to public
using (((bucket_id = 'ticket-photos'::text) AND ((storage.foldername(name))[1] = 'private'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "insert for authenticated lrl14v_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'monthly-reports'::text));



  create policy "select for authenticated lrl14v_0"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using ((bucket_id = 'monthly-reports'::text));



  create policy "update  lrl14v_0"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using ((bucket_id = 'monthly-reports'::text));



  create policy "update  lrl14v_1"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using ((bucket_id = 'monthly-reports'::text));



